version: '3.9'

services:
  backend:
    build:
      context: ./anime-catalog-backend
    networks:
      - dev
    expose:
      - "8000"

  frontend:
    build:
      context: ./anime-catalog-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev

networks:
  dev:
